#!/bin/env bash

## Setup
WorkDir=/etc/httpd/conf.d

## Create a backup of the latest config file
printf '%s\n' \
	"Backing up latest default Apache config..."
sudo cp -v $WorkDir/elemental_se_apache.conf \
	$WorkDir/elemental_se_apache.conf.bak.1

## Exit script if no custom SSL Apache config is found
if [[ ! -f $WorkDir/elemental_se_apache.conf.ssl ]]; then
	printf '\a\n%s\n%s\n' \
	"*** WARNING: Custom SSL Apache config was found." \
	"    Please upload a backup copy, or create a new one."
	exit 1
fi

## Restore the configuration
printf '%s\n' \
	"Restoring custom SSL Apache config..."
sudo cp $WorkDir/elemental_se_apache.conf.ssl \
	$WorkDir/elemental_se_apache.conf

## Test the configuration file
printf '%s\n' \
	"Performing Apache config test..."

## Warn if config test fails
if ! sudo service httpd configtest 2> >(grep -q "Syntax OK"); then
	printf '\a\n%s\n%s\n\n' \
		"*** WARNING: Apache config test has FAILED." \
		"    Please see the output below for reference:"
	sudo service httpd configtest
	printf '\n%s\n' \
		"Exiting without restarting Apache; SSL config was NOT restored."
	exit 1
else
	## Load the configuration if successful
	printf '%s\n' \
	"Apache config test passed; restarting Apache..."

	## Restart Apache web server
	sudo service httpd restart
	printf '\n%s\n' \
		"Done."
fi
